import yagmail
import os
from datetime import datetime
import pytz

# Gmail Configuration
EMAIL = "sd1898691@gmail.com"
APP_PASSWORD = "tfakvqqrbvajddoi"  # Your App Password

def send_email(to_email, file_path, patient_name="Patient", prediction=None):
    """
    Send professional medical report email with attachment using yagmail
    """
    try:
        print(f"Attempting to send email to: {to_email}")
        
        # Validate inputs
        if not to_email or not to_email.strip():
            return False, "Email address is empty"
        
        if not os.path.exists(file_path):
            return False, f"Report file not found at {file_path}"
        
        # Initialize yagmail
        yag = yagmail.SMTP(EMAIL, APP_PASSWORD)
        
        # Use Indian Standard Time (IST)
        IST = pytz.timezone("Asia/Kolkata")
        current_date = datetime.now(IST).strftime("%B %d, %Y at %I:%M %p")
        
        # Create email subject
        subject = "🏥 PneumoScreen AI - Your Medical Diagnostic Report"
        
        # Create email body (HTML and plain text combined)
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <div style="background: linear-gradient(135deg, #1f6feb, #388bfd); color: white; padding: 20px; text-align: center;">
                <h1>🏥 PneumoScreen AI</h1>
                <p>Deep Learning-Based Pneumonia Screening & Reporting System</p>
            </div>
            <div style="padding: 20px;">
                <h2>Dear {patient_name},</h2>
                <p>Your medical diagnostic report has been successfully generated by our AI system.</p>
                
                <div style="background: #f0f0f0; padding: 15px; margin: 10px 0;">
                    <strong>📋 Report Details:</strong><br>
                    • Generated: {current_date} (IST)<br>
                    • System Version: PneumoScreen AI v1.0
                </div>
                
                {f'''
                <div style="background: #e7f3ff; padding: 15px; margin: 10px 0; text-align: center;">
                    <strong>🎯 AI Prediction Result:</strong><br>
                    <span style="font-size: 20px; font-weight: bold; color: #1f6feb;">{prediction['class']}</span><br>
                    <small>Confidence: {prediction['confidence']:.2%}</small>
                </div>
                ''' if prediction else ''}
                
                <div style="background: #d4edda; padding: 15px; margin: 10px 0;">
                    <strong>📎 Attachment Information:</strong><br>
                    • Medical Report PDF is attached to this email
                </div>
                
                <div style="background: #fff3cd; padding: 15px; margin: 10px 0;">
                    <strong>⚠️ Important Notes:</strong><br>
                    • This report is AI-generated and should be reviewed by a healthcare professional<br>
                    • Keep this report for your medical records<br>
                    • Contact your doctor for clinical correlation
                </div>
                
                <p>Thank you for trusting PneumoScreen AI for your healthcare needs.</p>
                
                <p>Best regards,<br>
                <strong>PneumoScreen AI Team</strong></p>
            </div>
            <div style="text-align: center; font-size: 12px; color: #666; padding: 15px;">
                <p>© 2024 PneumoScreen AI | All Rights Reserved</p>
                <p>This is an automated message. Please do not reply directly to this email.</p>
            </div>
        </body>
        </html>
        
        PNEUMOSCREEN AI - MEDICAL REPORT
        
        Dear {patient_name},
        
        Your medical diagnostic report has been successfully generated by our AI system. 
        Please find the detailed report attached to this email.
        
        Report Details:
        - Generated: {current_date} (IST)
        - System Version: PneumoScreen AI v1.0
        
        {f"AI Prediction: {prediction['class']} (Confidence: {prediction['confidence']:.2%})" if prediction else ""}
        
        Important Notes:
        - This report is AI-generated and should be reviewed by a healthcare professional
        - Keep this report for your medical records
        - Contact your doctor for clinical correlation
        
        Best regards,
        PneumoScreen AI Team
        """
        
        # Send email with attachment
        yag.send(
            to=to_email,
            subject=subject,
            contents=body,
            attachments=file_path
        )
        
        print(f"✅ Email sent successfully to {to_email} at {current_date} IST")
        return True, "Email sent successfully"
        
    except Exception as e:
        error_msg = f"Failed to send email: {str(e)}"
        print(f"❌ {error_msg}")
        return False, error_msg
